Add country normalisation and validation utilities
This pull request adds some code to:
- check that a country is real<sup>1</sup>
- normalise it to the ‘correct’ name<sup>2</sup>
- work out how we should charge for posting a letter there<sup>3</sup>

Some examples:
```python
from notifications_utils.countries import Country
```

```python
country = Country('pitcairn')
country.canonical_name
>>> 'Pitcairn, Henderson, Ducie and Oeno Islands'
country.postage_zone
>>> 'rest of world'
```

```python
country = Country('Macedonia')
country.canonical_name
>>> 'North Macedonia'
country.postage_zone
>>> 'Europe'
```

```python
country = Country('scotland')
country.canonical_name
>>> 'United Kingdom'
```

If the country can’t be recognised a `CountryNotFound` exception will be
raised:
```python
country = Country('London')
CountryNotFoundError: 'Not a known country or territory (London)'
```

***

The sources are:
- The [graph data](https://github.com/alphagov/govuk-country-and-territory-autocomplete/blob/master/dist/location-autocomplete-graph.json) from the [GOV.UK Country and Territory autocomplete](https://alphagov.github.io/govuk-country-and-territory-autocomplete/examples/) which includes the canonical names for countries and territories, as well as a bunch of useful synonyms
- [Royal Mail’s list of countries in Europe](https://www.royalmail.com/international-zones#europe), edited to use the normalised names from the country register

We are also storing some data of our own:
- `uk-islands.txt` – a list of places whose addresses should not be
  normalised to _United Kindgom_, but should still be charged postage
  for the United Kingdom and allowed to choose between first and second
  class post
- `synonyms.json` – a hand crafted list of synonyms not covered by the
  Country and Territory autocomplete graph

***

1. Real according to the [country register](https://www.registers.service.gov.uk/registers/country) or [territory register](https://www.registers.service.gov.uk/registers/territory). That is to say it’s not a strict list of countries recognised by the UK.
2. Again, correct according to the registers, which are countries and
   territories recognised by the Foreign and Commonwealth Office
3. Postage can be _UK_, _Europe_ or _rest of world_
    - _UK_ is anything where the given country names maps to _United
      Kingdom_ (or _Jersey_, _Guernsey_ and _Isle of Man_)
    - Europe is places in the Royal Mail Europe postage zone, excluding
      the following which aren’t separate countries (up for debate
      whether we should reject these):
        - Azores
        - Canary Islands
        - Madeira
        - Balearic Islands
        - Corsica
    - _rest of world_ is any other recognised country or territory