Ignore error about import from `html` library
mypy says:
> error: Module `html` has no attribute `_replace_charref`  [attr-defined]

Typeshed contains external type annotations for the Python standard
library, and is used by mypy.

I’ve fixed this problem upstream in https://github.com/python/typeshed/pull/15925/files

This fix won’t be in mypy until the next feature release, so we need to
ignore the error until then.