Make `_MicrosecondAddingFormatterMixin` not a mixin
Mypy gives this error:
> error: `formatTime` undefined in superclass  [misc]

Mixins are hard to type hint.

Internet says:
> Typically, a mixin class is designed to be used with one specific base class. In such cases, it’s best to simply declare the mixin as a subclass of the base class, making it a regular subclass, even if it’s still not intended to be used directly.

– https://adamj.eu/tech/2025/05/01/python-type-hints-mixin-classes/

`BaseJsonFormatter` is a subclass of `logging.Formatter`:
https://github.com/nhairs/python-json-logger/blob/01cb83c1be1f26eb9f75cd3233b270fc06dd7962/src/pythonjsonlogger/core.py#L108C25-L108C42

Our `Formatter` is also a subclass of `logging.Formatter`.

So we don’t need to use a mixin.